# Numpy Exercise

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [18]:
# Create a 1-dimensional NumPy array using np.array()
matrix1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
matrix2 = np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
matrix3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
matrix1.shape, matrix2.shape, matrix3.shape

((3,), (2, 3), (2, 2, 3))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [19]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
matrix1.shape, matrix1.dtype, matrix1.size

((3,), dtype('int32'), 3)

In [20]:
# Attributes of 2-dimensional array
matrix2.shape, matrix2.dtype, matrix2.size

((2, 3), dtype('int32'), 6)

In [21]:
# Attributes of 3-dimensional array
matrix3.shape, matrix3.dtype, matrix3.size

((2, 2, 3), dtype('int32'), 12)

In [23]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
data = pd.DataFrame(matrix2, columns=['A', 'B', 'C'])
data

A  B  C
0  1  2  3
1  4  5  6

In [17]:
# Create an array of shape (10, 2) with only ones
array_ones = np.ones((10,2))
array_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
# Create an array of shape (7, 2, 3) of only zeros
array_zeros = np.zeros((7,2,3))
array_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [25]:
# Create an array within a range of 0 and 100 with step 3
array = np.arange(0, 100, 3)
array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [39]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(0, 10, (7,2))

array([[6, 1],
       [2, 0],
       [4, 0],
       [7, 0],
       [0, 1],
       [1, 5],
       [6, 4]])

In [37]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
randomArray = np.random.rand(3,5)
randomArray

array([[0.87146059, 0.80367208, 0.18657006, 0.892559  , 0.53934224],
       [0.80744016, 0.8960913 , 0.31800347, 0.11005192, 0.22793516],
       [0.42710779, 0.81801477, 0.86073058, 0.00695213, 0.5107473 ]])

In [4]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0, 10, (4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Ans: An array of size (4,6) with random numbers is generated.

Are the numbers in the array different or the same? Why do think this is?

Ans: The numbers are same. The numbers are same becaues we have kept a random seed of 42 while generating the numbers so it remains constant regardless of different systems.

In [42]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array = np.random.randint(1, 10, (3,7))

# Find the unique numbers in the array you just created
random_array

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2],
       [2, 4, 8, 7, 9, 8, 5]])

In [43]:
# Find the 0'th index of the latest array you created
random_array[0][0]

7

In [44]:
# Get the first 2 rows of latest array you created
random_array[:2]

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2]])

In [46]:
# Get the first 2 values of the first 2 rows of the latest array
random_array[:2, :2]

array([[7, 8],
       [4, 2]])

In [101]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array2 = np.random.randint(0, 10, (3,5))
array_ones2 = np.ones((3,5))
random_array2, array_ones2

(array([[6, 8, 8, 2, 2],
        [2, 3, 7, 5, 7],
        [0, 7, 3, 0, 7]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [102]:
# Add the two arrays together
sum = random_array2 + array_ones2
sum

array([[7., 9., 9., 3., 3.],
       [3., 4., 8., 6., 8.],
       [1., 8., 4., 1., 8.]])

In [103]:
# Create another array of ones of shape (5, 3)
array_ones3 = np.ones((5,3))
array_ones3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [104]:
# Try add the array of ones and the other most recent array together
sum += array_ones3

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

Ans: NumPy uses broadcasting rules to perform operations on arrays of different shapes. And these Shapes (3,5) (5,3) (3,5) aren't compatible for broadcasting.

How would you fix it?

Ans: We can fix this by Transpoing the Second Array which makes (3,5) (3,5) (3,5) shapes which will be compatible for broadcasting afterwards.

In [95]:
# Create another array of ones of shape (3, 5)
array_ones4 = np.ones((3,5))
array_ones4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [105]:
# Subtract the new array of ones from the other most recent array
sum -= array_ones4
sum

array([[6., 8., 8., 2., 2.],
       [2., 3., 7., 5., 7.],
       [0., 7., 3., 0., 7.]])

In [106]:
# Multiply the ones array with the latest array
mult = array_ones4 * sum
mult

array([[6., 8., 8., 2., 2.],
       [2., 3., 7., 5., 7.],
       [0., 7., 3., 0., 7.]])

In [107]:
# Take the latest array to the power of 2 using '**'
mult ** 2

array([[36., 64., 64.,  4.,  4.],
       [ 4.,  9., 49., 25., 49.],
       [ 0., 49.,  9.,  0., 49.]])

In [108]:
# Do the same thing with np.square()
np.square(mult)

array([[36., 64., 64.,  4.,  4.],
       [ 4.,  9., 49., 25., 49.],
       [ 0., 49.,  9.,  0., 49.]])

In [109]:
# Find the mean of the latest array using np.mean()
np.mean(mult)

4.466666666666667

In [110]:
# Find the maximum of the latest array using np.max()
np.max(mult)

8.0

In [111]:
# Find the minimum of the latest array using np.min()
np.min(mult)

0.0

In [112]:
# Find the standard deviation of the latest array
np.std(mult)

2.777688887466621

In [113]:
# Find the variance of the latest array
np.var(mult)

7.715555555555554

In [114]:
# Reshape the latest array to (3, 5, 1)
np.reshape(mult, (3,5,1))

array([[[6.],
        [8.],
        [8.],
        [2.],
        [2.]],

       [[2.],
        [3.],
        [7.],
        [5.],
        [7.]],

       [[0.],
        [7.],
        [3.],
        [0.],
        [7.]]])

In [115]:
# Transpose the latest array
mult.T

array([[6., 2., 0.],
       [8., 3., 7.],
       [8., 7., 3.],
       [2., 5., 0.],
       [2., 7., 7.]])

What does the transpose do?

Ans: Transpose is an operation that flips a matrix over its diagonal, swapping its rows with columns. So in above output the rows and columns were swapped.

In [69]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random1 = np.random.randint(0, 10, (3,3))
random2 = np.random.randint(0, 10, (3,2))

In [71]:
# Perform a dot product on the two newest arrays you created
np.dot(random1, random2)

array([[67, 93],
       [79, 81],
       [92, 98]])

In [72]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random3 = np.random.randint(0, 10, (4,3))
random4 = np.random.randint(0, 10, (4,3))

In [73]:
# Perform a dot product on the two newest arrays you created
np.dot(random3, random4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

Ans: Since the dimension aren't matching for doing a matrix multiplication. So we can do a Transpose of second matrix/array and perform the matrix multiplication.

In [74]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
np.dot(random3, random4.T)

array([[56, 11, 60,  6],
       [ 0, 24, 36, 21],
       [42, 17, 40,  4],
       [ 0,  4, 16,  8]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Ans: Because the dimension of the second matrix which was (4,3) was changed to (3,4). Now the first matrix is in (4 x 3) form and second matrix is in (3 x 4) form which will be in the form (4 x 4) after dot product so the dot product happens. 

Checking out the documentation on np.dot() may help, as well as reading Math is Fun's guide on the dot product.

Let's now compare arrays.

In [8]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array1 = np.random.randint(0, 10, (3,3))     
array2 = np.random.randint(0, 10, (3,3))
array1, array2

(array([[8, 0, 9],
        [2, 6, 3],
        [8, 2, 4]]),
 array([[2, 6, 4],
        [8, 6, 1],
        [3, 8, 1]]))

In [9]:
# Compare the two arrays with '>'
array1 > array2

array([[ True, False,  True],
       [False, False,  True],
       [ True, False,  True]])

What happens when you compare the arrays with >?

Ans: When comparing the arrays with ">" both arrays are compared element wise and the output is given in the form of "True" and "False" after comparing each elements in it's position on both arrays. Example:- 8 is greater than 2 so it returns True.

In [78]:
# Compare the two arrays with '>='
array1 >= array2

array([[False,  True,  True],
       [ True, False,  True],
       [ True, False,  True]])

In [79]:
# Find which elements of the first array are greater than 7
mask = array1 > 7
array1[mask]

array([9])

In [81]:
# Which parts of each array are equal? (try using '==')
mask = array1 == array2
array1[mask]

array([5])

In [82]:
# Sort one of the arrays you just created in ascending order
np.sort(array1)

array([[4, 5, 9],
       [3, 6, 6],
       [0, 5, 7]])

In [83]:
# Sort the indexes of one of the arrays you just created
np.argsort(array1, axis=1)

array([[0, 2, 1],
       [1, 0, 2],
       [1, 2, 0]], dtype=int64)

In [85]:
# Find the index with the maximum value in one of the arrays you've created
np.unravel_index(np.argmax(array1), array1.shape)

(0, 1)

In [88]:
# Find the index with the minimum value in one of the arrays you've created
np.unravel_index(np.argmin(array2), array2.shape)

(2, 0)

In [89]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(array1, axis=1)

array([1, 0, 0], dtype=int64)

In [90]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(array1, axis=0)

array([0, 2, 0], dtype=int64)

In [91]:
# Create an array of normally distributed random numbers
normal_distrib_arr = np.random.randn(3,4)
normal_distrib_arr

array([[ 0.7896728 ,  0.43148946, -1.0967523 , -0.68230156],
       [ 0.88751161,  0.60548313, -0.72029799, -0.26993377],
       [-0.14346223,  0.61700378,  1.2489407 ,  0.06564916]])

In [92]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])